CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.10.sdk       # [osx]

macos_min_version:             # [osx]
  - 10.10                      # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.10                      # [osx]

moose_mpich:
  - 3.3.2 build_3

moose_libmesh_vtk:
  - 6.3.0 build_3

SHORT_VTK_NAME:
  - 6.3

libblas:
  - 3.8.0 15_openblas # [osx]

libcblas:
  - 3.8.0 15_openblas # [osx]

liblapack:
  - 3.8.0 15_openblas # [osx]

libopenblas:
  - 0.3.8 h3d69b6c_0  # [osx]

libpng:
  - 1.6.37 h2573ce8_0 # [osx]
  - 1.6.37 hed695b0_0 # [linux]

pin_run_as_build:
  moose_mpich: x.x.x
  libblas: x.x.x
  libcblas: x.x.x
  liblapack: x.x.x

pr_num:
  - 0
